name: Matrix build
on:
  workflow_dispatch:
jobs:

  build-matrix:
    runs-on: ubuntu-latest

    outputs:
      repos: ${{ steps.matrix.outputs.repos }}

    steps:
      - uses: ices-tools-prod/ices-tools-prod-actions-checkout@main

      - name: Build matrix
        id: matrix
        run: |
          echo "repos=$(jq -c '[.[].nameWithOwner]' repos.json)" >> $GITHUB_OUTPUT
